httpd:
  repository: docker-01.progi.loc:5000/dev/httpd-lc2
  tag: latest 
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  pullSecrets:
    - Regcred

jboss:
  repository: docker-01.progi.loc:5000/dev/laboconnect
  image: docker-01.progi.loc:5000/dev/laboconnect
  tag: LC03.06mbi
  pullPolicy: IfNotPresent

postgres:
  password: KuFM4LMylb
  port: 5433 

pass_lc: random1
pass_mss_rw: random2
pass_mss_ro: random3

node: docker-01

VersionLaboconnect: LC03.06
externalDatabase:
  ## Database host
  host: localhost

  ## non-root Username for Wordpress Database
  user: bn_wordpress

  ## Database password
  password: ""

  ## Database name
  database: bitnami_wordpress

  ## Database port number
  port: 3306

defaultpasswords: True

postgres:
  repository: docker-01.progi.loc:5000/dev/postgres-lc
  tag: latest
  pullPolicy: IfNotPresent
serviceType: NodePort

nodePorts:
#  http: ""
  https: ""
serviceExternalTrafficPolicy: Local

## Allow health checks to be pointed at the https port
healthcheckHttps: false
