image:
  #repository: docker-01.progi.loc:5000/dev/httpd-lc2
  tag: latest 
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  pullSecrets:
    - Regcred

jboss:
  repository: docker-01.progi.loc:5000/dev/laboconnect
  image: docker-01.progi.loc:5000/dev/laboconnect
  tag: LC03.06mbi
  pullPolicy: IfNoPresent

env:
  httphost: docker-01
  postgreshost: docker-01
  jbosshost: docker-01
wordpressUsername: user

wordpressEmail: user@example.com

wordpressFirstName: FirstName

wordpressLastName: LastName

wordpressBlogName: User's Blog!

## Table prefix
## ref: https://github.com/bitnami/bitnami-docker-wordpress#environment-variables
##
wordpressTablePrefix: wp_

## Set to `yes` to allow the container to be started with blank passwords
## ref: https://github.com/bitnami/bitnami-docker-wordpress#environment-variables
allowEmptyPassword: "yes"

externalDatabase:
## All of these values are only used when mariadb.enabled is set to false
  ## Database host
  host: localhost

  ## non-root Username for Wordpress Database
  user: bn_wordpress

  ## Database password
  password: ""

  ## Database name
  database: bitnami_wordpress

  ## Database port number
  port: 3306

##
## MariaDB chart configuration
##
mariadb:
  repository: docker-01.progi.loc:5000/dev/postgres-lc
  tag: latest

serviceType: NodePort
##
## serviceType: NodePort
## nodePorts:
##   http: <to set explicitly, choose port between 30000-32767>
##   https: <to set explicitly, choose port between 30000-32767>
nodePorts:
#  http: ""
  https: ""
## Enable client source IP preservation
## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
##
serviceExternalTrafficPolicy: Local

## Allow health checks to be pointed at the https port
healthcheckHttps: false
