apiVersion: v1
kind: Service
metadata:
  name: init-sv{{.Values.numb}}
  labels:
    app: init
spec:
  type: NodePort
  ports:
  - name: init
    port: 6060
    #nodePort: 
    targetPort: 6060
  selector:
    app: init{{.Values.numb}}
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-sv{{.Values.numb}}
#  namespace: lc
  labels:
    app: LaboConnect
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      targetPort: 443
      #nodePort: 30111
      {{- if (and (eq .Values.serviceType "NodePort") (not (empty .Values.nodePorts.https)))}}
      nodePort: {{ .Values.nodePorts.https }}
      {{- end }}
  selector:
    app: LaboConnect{{.Values.numb}}0
#    app: {{ template "fullname" . }}
#    app: LaboConnect
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-sv{{.Values.numb}}
#  namespace: lc
  labels:
    app: Laboconnect2
#    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#    release: "{{ .Release.Name }}"
#    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
  - name: postgres
    port: 5432
    nodePort: {{ .Values.nodePorts.postgres }}
    targetPort: 5432
  selector:
    app: LaboConnect{{.Values.numb}}2
---
apiVersion: v1
kind: Service
metadata:
  name: laboconnect-sv{{.Values.numb}}
#  namespace: lc
  labels:
    app: Laboconnect3
#    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#    release: "{{ .Release.Name }}"
#    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
  - name: postgres
    port: 7070
    nodePort: 30888
    targetPort: 7070
  selector:
    app: LaboConnect{{.Values.numb}}3
#
